apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dep
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      hostname: postgres
      containers:
      - name: postgres
        image: postgres:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        - containerPort: 22
        
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: psqlconfig
              key: PSQL_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            configMapKeyRef:
              name: psqlconfig
              key: PSQL_USERNAME
      restartPolicy: Always
---

# https://kubernetes.io/docs/concepts/configuration/configmap/
kind: ConfigMap
apiVersion: v1
metadata:
  name: psqlconfig
  namespace: default
data:
  PSQL_USERNAME: postgres 
  PSQL_PASSWORD: password
  PSQL_HOSTNAME: "10.96.144.67"  
---

kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
---

# kind: Endpoints
# apiVersion: v1
# metadata:
#   name: postgres
#   namespace: default
# subsets:
#   - hostname: postgres
#     ports:
#       - port: 5432

---

apiVersion: v1
kind: Pod
metadata:
  name: ohcs-pd
  namespace: default
  labels:
    name: ohcs
spec:
  containers:
  - name: ohcs
    image: docker.io/devopsxpro/ohcs:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
        name: http 
      - containerPort: 22
        name: ssh
    env:
      - name: PSQL_HOSTNAME
        valueFrom:
          configMapKeyRef:
            name: psqlconfig
            key: PSQL_HOSTNAME
      - name: PSQL_PASSWORD
        valueFrom:
          configMapKeyRef:
            name: psqlconfig
            key: PSQL_PASSWORD
      - name: PSQL_USERNAME
        valueFrom:
          configMapKeyRef:
            name: psqlconfig
            key: PSQL_USERNAME         
  restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: ohcs
spec:
  selector:
    app: ohcs
  ports:
  - port: 80
    targetPort: 80


