version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.12.0
  aws-cli: circleci/aws-cli@2.0.3


commands:
  delete_cluster_core_and_nodes:
    description: destroy cluster workload nodes and loadbalancers
    parameters:
      awsConfigStatus:
        type: enum
        default: "yes"
        enum: ["yes", "no"]
    steps:
      - run:
          name: delete cluster nodes
          when: on_fail
          working_directory: ".circleci/deployment/IaC"
          command: |
            awsStatus=<<parameters.awsConfigStatus>>
            if [ "$awsStatus" == "no" ]; then echo "Configure AWS CLI"; exit 1; fi;

            chmod +x ./xbin/delete-cluster-nodes.sh
            ./xbin/delete-cluster-nodes.sh
      - run:
          name: delete cluster elbs
          when: on_fail
          working_directory: ".circleci/deployment/IaC"
          command: |
            chmod +x ./xbin/delete-alb-instances.sh
            ./xbin/delete-alb-instances.sh
      - run:
          name: delete network resources except VPC
          when: on_fail
          working_directory: ".circleci/deployment/IaC"
          command: |
            chmod +x ./xbin/delete-network-resources.sh
            ./xbin/delete-network-resources.sh "exclude-vpc"

      - run:
          name: delete vpc and associated security groups
          when: on_fail
          working_directory: ".circleci/deployment/IaC"
          command: |
            chmod +x ./xbin/delete-network-resources.sh
            ./xbin/delete-network-resources.sh "include-vpc"
            
  cache_handle:
    description: helper command to store or retrieve values from MemoStash
    parameters:
      operation:
        type: enum
        default: 'GET'
        enum: ['GET', 'PUT']
      key:
        type: string 
      value: 
        type: string
    steps:
      - run:
          command: |
            OPER=<< parameters.operation >>;
            KEY=<< parameters.key >>;
            if [ "$OPER" == "GET" ]; then
              curl -H "token: ${MEM_ST_TOKEN}" --request GET https://api.memstash.io/values/$KEY
            else
              VALUE=<< parameters.value >>
              curl -H "Content-Type: text/plain" -H "token: ${MEM_ST_TOKEN}" --request PUT --data "$VALUE" https://api.memstash.io/values/$KEY;
            fi;

  setup_awscli:
    steps:
      - aws-cli/install
      - run:
          name: configure aws profile
          command: |
            aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
            aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
            aws configure set aws_default_region ${AWS_DEFAULT_REGION}

  install_envsubs:
    steps:
      - run:
          name: update apt and install gettext-base(envSUBST)
          command: |
            # sudo apt-get update -y
            sudo apt install -y gettext-base --fix-missing


jobs:
  build:
    description: Analyze backend source code
    docker:
      - image: circleci/python:3.8.4
    steps:
      - checkout
      - run:
          name: create environment to run code analyze
          command: |
            # require virtural environ 
            make setup
      - run:
          name: install dependencies
          command: |
            # install deps
            make install
      - run:
          name: run code lints
          command: |
            # format the source code 
            make lint
      - save_cache:
          paths:
            - ".venv"
          key: deps-Pipfile.lock
    
  coverage_tests:
    docker:
      - image: circleci/python:3.8.4
      - image: circleci/postgres:9.6.16
        environment:
          POSTGRES_USERNAME: ${POSTGRES_USERNAME}
          POSRGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_PORT: 5432
    environment:
      POSTGRES_HOSTNAME: localhost   
    steps:
      - checkout
      - restore_cache:
          keys: 
            - deps-Pipfile.lock
      - run:
          name: Install dependencies
          command: |
            sudo apt update 
            sudo apt-get install -y postgresql-client --fix-missing
            # make install    
      - run:
          name: run local database migrations tests           
          command: |
            export FLASK_APP=${OPENHCS_APP}
            pipenv run flask populate --tables=all; 
            psql -h $POSTGRES_HOSTNAME -U $POSTGRES_USERNAME -d postgres -w -c "\l"
            psql -h $POSTGRES_HOSTNAME -U $POSTGRES_USERNAME -d postgres -w -c "\dt"
            # make migrations
      - run:
          name: run code coverage tests 
          command: |
            # pass IF coverage > 70%
            make test

  make_migrations:
    docker:
      - image: circleci/python:3.8.4
    steps:
      - checkout
      - restore_cache:
          keys: 
            - deps-Pipfile.lock
      - run:
          name: prepare environment variables for migrations 
          command: |
            cat > ./openhcs/.env \<< EOF 
            FLASK_ENV=production
            PSQL_DB_PROFILES=${PSQL_DB_PROFILES}
            PSQL_DB_SCHEDULES=${PSQL_DB_SCHEDULES}
            PSQL_DB_SUBSCRIBERS=${PSQL_DB_SUBSCRIBERS}
            PSQL_DB_BOOKING=${PSQL_DB_BOOKING}
            PSQL_HOSTNAME=${PSQL_HOSTNAME}
            PSQL_PASSWORD=${PSQL_PASSWORD}
            PSQL_USERNAME=${PSQL_USERNAME}
            EOF
            
      - run:
          name: run migrations
          command: |
            # execute flask-migrate
            export FLASK_APP=${OPENHCS_APP}
            make migrations

  build_docker_image:
    description: build the docker image from code
    machine: 
      image: ubuntu-2004:202107-02
    environment:
      OPENHCS_IMAGE_TAG: "${DOCKER_ID}/openhcs:latest"
    steps:
      - checkout
      - run:
          name: login to docker hub
          command: docker login --username ${DOCKER_ID} --password ${DOCKER_PASSWORD}
      - run:
          name: build the openhcs docker image
          command: |
            docker build . -t openhcs:latest
            export docker_path=${DOCKER_ID}/openhcs:latest
            docker tag openhcs:latest $docker_path
      - run:
          name: push openhcs image to docker hub
          command: |
            export docker_path=${DOCKER_ID}/openhcs:latest
            docker push $docker_path

  create_cluster_infrastructure:
    description: provision the cluster infrastructue 
    docker: 
      - image: cimg/base:stable
      # - image: amazon/aws-cli
    environment:
      CLUSTER_IAC_STACK_NAME: openhcs-iacode
    steps:
      - checkout
      - setup_awscli
      - run:
          name: create the network infrastructure
          working_directory: ".circleci/deployment/IaC"
          no_output_timeout: 20m
          command: |
            aws cloudformation deploy --stack-name ${CLUSTER_IAC_STACK_NAME} \
            --template-file clusterIaC.yml --region "${AWS_DEFAULT_REGION}" \
            --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" \
            --profile default 
            
      # - delete_cluster_core_and_nodes:
      #     awsConfigStatus: "yes"  

  create_cluster_core:
    description: create cluster control plane and workload node 
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_awscli
      - aws-eks/install-eksctl
      - run:
          name: create cluster and managed node groups
          working_directory: ".circleci/deployment/IaC"
          no_output_timeout: 20m
          command: |
            aws cloudformation deploy --stack-name ${CLUSTER_STACK_NAME} \
            --template-file clusterCore.yml --region ${AWS_DEFAULT_REGION} \
            --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" \
            --parameter-overrides ClusterIaCStackName="${CLUSTER_IAC_STACK_NAME}" --profile default 
            
      - run:
          name: enable cluster logging types 
          command: |
            eksctl utils update-cluster-logging --cluster $CLUSTER_NAME  --enable-types=all --approve
      - delete_cluster_core_and_nodes:
          awsConfigStatus: "yes"

  configure_cluster_core:
    description: configure cluster kubernetes 
    docker:
      - image: circleci/python:3.8.4
    environment:
      GREEN_SERVER_PORT: 80
      # To remove
    steps:
      - checkout
      - setup_awscli
      - kubernetes/install-kubectl:
          kubectl-version: latest
      - aws-eks/install-eksctl
      - aws-eks/update-kubeconfig-with-authenticator: 
          aws-region: ${AWS_DEFAULT_REGION}
          cluster-name: ${CLUSTER_NAME}
      - install_envsubs
      - run:
          name: test kubernetes config file 
          command: |
            SVCS=$(kubectl  get services -n kube-system -o json )
            
            # Abort deployment if empty 
            if [[ -n $( echo "$SVCS" | grep "kube-system" ) ]]; then 
              echo "Cofigured Successfully";
              ls ~/.kube
            else
              echo "$SVCS"
              exit 1;
            fi;
      - run:
          name: create services for app deployment
          working_directory: ".circleci/deployment/K8s"  
          command: |
            # create services
            chmod +x ./xbin/services-init.sh
            ./xbin/services-init.sh $GREEN_SERVER_PORT ./services.yml;

            # kubectl wait --for=condition=available --timeout=120s services -n default -l 'environ in (production, staging)' ;
      # - run:
      #     name: create alb ingresses
      #     working_directory: ".circleci/deployment/K8s"
      #     command: |
      #       kubectl apply -f ingresses.yml
      #       sleep 10s
      #       kubectl describe ingresses -n default
      - run:
          name: create secretes 
          working_directory: ".circleci/deployment/K8s"
          command: |          
            # create secrets
            chmod +x ./xbin/secrets-init.sh
            ./xbin/secrets-init.sh ./secrets.yml

            kubectl get secrets -n default
      # persist the kubeconfig file
      - run:
          name: create config maps 
          working_directory: ".circleci/deployment/K8s"
          command: |
            # create configmaps
            chmod +x ./xbin/configs-init.sh
            ./xbin/configs-init.sh ./configmaps.yml

      - persist_to_workspace:
          root: ~/
          paths:
            - ".kube"
      - delete_cluster_core_and_nodes:
          awsConfigStatus: "yes"
 
  deploy_staging_green_k8s:
    description: >- 
      Deploy API server kubernetes in staging environment at green context.
    docker:
      - image: circleci/python:3.8.4
    environment:
      ENVIRON: staging     # environ for the deployment
      SERVER_PORT: 80      # web server port number
      VERSION: 1.0.1          # deployment version
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - kubernetes/install-kubectl:
          kubectl-version: latest 
      - install_envsubs
      - setup_awscli
      # - aws-eks/install-eksctl
      # - run:
      #     name: create kubeconfig
      #     command: |
      #       eksctl utils write-kubeconfig --cluster $CLUSTER_NAME --region $AWS_DEFAULT_REGION
      - run:
          name: make staging deployment
          working_directory: ".circleci/deployment/K8s"
          command: |
            OPENHCS_IMAGE="${DOCKER_ID}/openhcs:latest"   # docker image
            chmod +x xbin/deploy-init.sh
            # execute the deployment of app in the staging environment
            ./xbin/deploy-init.sh $ENVIRON $SERVER_PORT $VERSION $OPENHCS_IMAGE "./deployments.yml"
            
            kubectl get deployments -n default -l tier=backend,environ=$ENVIRON,context=green;            
      - run: 
          name: make smoke test on staging green deployment 
          working_directory: ".circleci/deployment/K8s"
          command: |
            # get the url of staging green app
            kubectl wait --for=condition=Ready=true --timeout=120s pods -l environ="staging",app="openhcs"
            export HOSTNAME=$(kubectl get configmaps -n default -l environ=staging,app=openhcs -o jsonpath="{.items[].data.SERVER_HOSTNAME}")
             
            URL="http://${HOSTNAME}:$SERVER_PORT"
          
            until [[ -n $( curl -sS "$URL" | grep "ok" ) ]]; do
              echo "Waiting for response from server: $URL"
              sleep 15s
            done;

            echo -e "\nStaging environment accessible from: $URL\n\n $(curl -sS $URL ) ";

      - delete_cluster_core_and_nodes:
            awsConfigStatus: "yes"
   
  deploy_production_blue_k8s:
    description: >-
      Depeloy in production production blue context (IF pass smoke test) and make smoke tests.
    docker:
      - image: circleci/python:3.8.4
    environment:
      SERVER_PORT: 443
      ENVIRON: production
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - kubernetes/install-kubectl:
          kubectl-version: latest 
      - install_envsubs
      - setup_awscli
      # - aws-eks/install-eksctl
      # - run:
      #     name: create kubeconfig
      #     command: |
      #       eksctl utils write-kubeconfig --cluster $CLUSTER_NAME --region $AWS_DEFAULT_REGION
      - run:
          name: deploy the app
          working_directory: ".circleci/deployment/K8s"
          command: |
            OPENHCS_IMAGE="${DOCKER_ID}/openhcs:latest"   # docker image

            # retrieve the staging deployment version
            VERSION=$( kubectl  get deployments -n default -l environ='staging',tier=backend,context=green -o jsonpath="{.items[0].metadata.labels.version}");
            
            chmod +x ./xbin/deploy-init.sh
            ./xbin/deploy-init.sh $ENVIRON $SERVER_PORT $VERSION $OPENHCS_IMAGE "./deployments.yml" ;
            
            kubectl get deployments -n default;

      - run:
          name: make in production smoke tests 
          command: |

            # get the url of in production blue app
            kubectl wait --for=condition=Ready=true --timeout=120s pods -l environ="production",app="openhcs";
            export HOSTNAME=$(kubectl get configmaps -n default -l environ=production,app=openhcs -o jsonpath="{.items[].data.SERVER_HOSTNAME}")
            
            URL="http://${HOSTNAME}:$SERVER_PORT"        

            # check in production app status is ok
            until [[ -n $( curl -sS "$URL" | grep "ok" ) ]]; do
              echo "Waiting for response from server: $URL"
              sleep 15s
            done;

            if [[ $? == 0  ]]; then 
              echo -e "\nProduction environment accessible from: $URL\n\n $(curl -sS $URL ) ";
            else
              # eliminate in production app if status is NOT ok, and exit with failure
              kubectl delete deployments/${PRO_OPENHCS_DPY} -n default;
              exit 1
            fi;
      - delete_cluster_core_and_nodes:
          awsConfigStatus: "yes"

  clean_up_deployment_stacks:
    docker:
      - image: circleci/python:3.8.4
    steps:
      - checkout
      - setup_awscli
      - attach_workspace:
          at: ~/
      - kubernetes/install-kubectl:
          kubectl-version: latest
      - run:
          name: Eliminate staging deploymemt
          command: |
            # eliminate the in staging deployment
              kubectl delete deployments/${STAG_OPENHCS_DPY} --namespace default
              kubectl wait --for=delete --timeout=60s pods -l environ="staging",app="openhcs";
              kubectl get deployments;
      - run:
          name: delete cluster nodes
          working_directory: ".circleci/deployment/IaC"
          no_output_timeout: 20m
          command: |
            chmod +x ./xbin/delete-cluster-nodes.sh
            ./xbin/delete-cluster-nodes.sh
      - run:
          name: delete cluster elbs
          working_directory: ".circleci/deployment/IaC"
          no_output_timeout: 20m
          command: |
            chmod +x ./xbin/delete-alb-instances.sh
            ./xbin/delete-alb-instances.sh
      
      - run:
          name: delete network resources except VPC
          working_directory: ".circleci/deployment/IaC"
          no_output_timeout: 20m
          command: |
            chmod +x ./xbin/delete-network-resources.sh
            ./xbin/delete-network-resources.sh "exclude-vpc"

      - run:
          name: delete vpc and associated security groups
          working_directory: ".circleci/deployment/IaC"
          no_output_timeout: 20m
          command: |
            chmod +x ./xbin/delete-network-resources.sh
            ./xbin/delete-network-resources.sh "include-vpc"
          
 
workflows:
  OpenHeathCare CICD:
    jobs:
      - build
      - coverage_tests:
          context: THEOPENHCS
          requires:
            - "build"
      - review_codebase:
          type: approval
          requires:
            - coverage_tests
      - make_migrations:
          context: THEOPENHCS
          requires:
            - "coverage_tests"
            - "review_codebase"
          filters:
            branches:
              only: [main]
      - build_docker_image:
          context: THEOPENHCS
          filters:
            branches:
              only: [main]
          requires:
            - coverage_tests
            - make_migrations
      - review_built_image:
          requires: [build_docker_image]
          type: approval
      
      - create_cluster_infrastructure:
          context: THEOPENHCS
          pre-steps:
            - run:
                name: Notify administrator
                command: |
                  echo  "Send notification from here"
          requires:
            - review_built_image
            - build_docker_image
          filters:
            branches:
              only: [main]

      - create_cluster_core:
          context: THEOPENHCS
          requires:
            - create_cluster_infrastructure

      - configure_cluster_core:
          context: THEOPENHCS
          requires:
            - "create_cluster_core"
          filters:
            branches:
              only: [main]
          post-steps:
            - run:
                name: Notify administrator
                command: |
                  echo "Send notification from here"
      - deploy_staging_green_k8s:
          context: THEOPENHCS
          requires:
            - "configure_cluster_core"

      - deploy_production_blue_k8s:
          context: THEOPENHCS
          requires:
            - "deploy_staging_green_k8s"
      
      - hold:
          type: approval
          requires:
            - "deploy_production_blue_k8s"
      - clean_up_deployment_stacks:
          context: THEOPENHCS
          requires:
            - "hold"
          pre-steps:
            - run:
                name: notify_product_engineer
                command: echo "Deployment complete"