# https://kubernetes.io/docs/concepts/configuration/configmap/
kind: ConfigMap
apiVersion: v1
metadata:
  name: psqlconfig
  namespace: default
data:
  PSQL_DB_PROFILES: profiles 
  PSQL_DB_SUBSCRIBERS: subscribers
  PSQL_DB_SCHEDULES: schedules 
  PSQL_DB_BOOKING: booking

--- 
# https://kubernetes.io/docs/concepts/configuration/configmap/
kind: ConfigMap
apiVersion: v1
metadata:
  name: staging-svrconfig
  namespace: default
  labels:
    environ: staging
    app: openhcs
data:
  SERVER_HOSTNAME: ${SERVER_HOSTNAME_STAG}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: production-svrconfig
  namespace: default
  labels:
    environ: production
    app: openhcs
data:
  SERVER_HOSTNAME: ${SERVER_HOSTNAME_PRO}
