# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: coresecrets
  namespace: default
type: Opaque
stringData:
  PSQL_USERNAME: "${PSQL_USERNAME}"
  PSQL_PASSWORD: "${PSQL_PASSWORD}"
  PSQL_HOSTNAME: "${PSQL_HOSTNAME}"
  SECRET_KEY: "${SECRET_KEY}"
---
