apiVersion: v1
kind: PersistentVolume
metadata:
  name: openhcsvolume
  namespace: stagging
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  local:
    path: /usr/src
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - {key: environ, operator: In, values: [stagging, production]}

---
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhcspvclaim
  namespace: stagging
  labels:
    app: openhcs
spec:
  storageClassName: slow
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      environ: stagging
---
