Parameters:
  CidrBlockForVPC:
    Default: 187.0.0.0/24
    Description: CidrBlockForVPC
    Type: String
  CidrBlockForSubnet:
    Default: 187.0.0.0/25
    Description: Cidr Block For Subnet1
    Type: String



Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 
        !Ref CidrBlockForVPC

  Subnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Ref AvailabilityZoneForSubnet1
      CidrBlock: !Ref CidrBlockForSubnet
    

  LoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Scheme: internal
      Subnets:
        - !Ref Subnet1
        # - !Ref Subnet2
  TargetGroup1:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Port: 1000
      Protocol: HTTP
      VpcId: !Ref VPC